# Generated by Django 5.2.14 on 2026-06-03 02:17

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_enable_rls_django_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentometodologico',
            name='conteudo_texto',
            field=models.TextField(help_text='Conteúdo textual completo extraído da documentação do IBGE'),
        ),
        migrations.AlterField(
            model_name='documentometodologico',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, help_text='Data da última atualização deste documento no banco'),
        ),
        migrations.AlterField(
            model_name='documentometodologico',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=1536, help_text='Vetor de embeddings (1536 dims) para similaridade de cosseno'),
        ),
        migrations.AlterField(
            model_name='documentometodologico',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='documentometodologico',
            name='titulo',
            field=models.CharField(help_text='Título do documento ou nota metodológica', max_length=255),
        ),
        migrations.AlterField(
            model_name='metricasocioeconomica',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='metricasocioeconomica',
            name='regiao',
            field=models.CharField(help_text='Região de abrangência (Ex: Brasil, SP, RJ)', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='metricasocioeconomica',
            constraint=models.UniqueConstraint(fields=('data', 'tipo_metrica', 'regiao', 'estado'), name='unique_metrica_por_data_regiao'),
        ),
    ]
